version: '3'

# .prd.env:
#    FRONTEND__API_URL=http://backend-prd:8080/api/v1
#    BACKEND__DB_URL="sqlite:////app/db/trainr.db"
#    BACKEND__HB_FAN_DEVICE_ID=__fill_me__
#    BACKEND__HB_FAN_IP=__fill_me__
#    BACKEND__HB_FAN_LOCAL_KEY=__fill_me__
#    BACKEND__HUE_BRIDGE_IP=__fill_me__
#    BACKEND__HUE_BRIDGE_USERNAME=__fill_me__
#    BACKEND__HUE_BRIDGE_GROUP_NAME=__fill_me__

services:
  backend:
    container_name: backend-prd
    image: mariuszgorski/trainr-backend:latest
    networks:
      - trainr-prd-network
    volumes:
      - trainr-prd-backend-db:/app/db
    ports:
      - 8080:8080
    env_file:
      - .prd.env
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/health || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    depends_on:
      - postgresql

  frontend:
    container_name: frontend-prd
    image: mariuszgorski/trainr-frontend:latest
    networks:
      - trainr-prd-network
    ports:
      - 3000:3000
      - 8000:8000
    env_file:
      - .prd.env
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8000/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 180s
      timeout: 10s

networks:
  trainr-prd-network:

volumes:
  trainr-prd-backend-db:
    driver: local
