version: '3'

services:
  backend:
    container_name: backend-prd
    image: mariuszgorski/trainr-backend:latest
    networks:
      - trainr-prd-network
    volumes:
      - trainr-prd-backend-db:/app/db
    ports:
      - 8080:8080
    environment:
      BACKEND__DB_URL: sqlite:////app/db/trainr.db
    env_file:
      - .env

  frontend:
    container_name: frontend-prd
    image: mariuszgorski/trainr-frontend:latest
    networks:
      - trainr-prd-network
    ports:
      - 3000:3000
      - 8000:8000
    environment:
      FRONTEND__API_URL: http://backend-prd:8080/api/v1

networks:
  trainr-prd-network:

volumes:
  trainr-prd-backend-db:
    driver: local
