FROM python:3.9

WORKDIR /app/trainr

COPY trainr/backend backend
COPY trainr/utils.py .
COPY requirements-backend.txt requirements.txt

ENV VIRTUAL_ENV=/app/trainr/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PYTHONPATH=$VIRTUAL_ENV:/app

RUN python3.9 -m venv $VIRTUAL_ENV && \
    pip install -r requirements.txt

CMD ["uvicorn", "trainr.backend.api.main:app", "--host", "0.0.0.0", "--port", "8080"]

