FROM python:3.9

ARG API_URL=http://localhost:3000

WORKDIR /app/trainr

COPY trainr/frontend frontend
COPY trainr/utils.py .
COPY requirements-frontend.txt requirements.txt

ENV VIRTUAL_ENV=/app/trainr/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PYTHONPATH=$VIRTUAL_ENV:/app

RUN python3.9 -m venv $VIRTUAL_ENV && \
    pip install -r requirements.txt

WORKDIR /app/trainr/frontend

RUN reflex init

CMD ["reflex", "run"]
