quotes = [
    "Pedal with the power of the dark side, my apprentice!",
    "In every revolution, feel the force within your pedals!",
    "Cyclists embrace pain; it makes them stronger, as does the Force.",
    "Ride relentlessly, young one, and let the dark side guide you!",
    "The road to victory is paved with discipline and determination.",
    "Feel the wind, sense the speed, embrace the cycling Force!",
    "Your strength is as boundless as the power of the dark side!",
    "On the bike, as in life, control your destiny with precision.",
    "Pedal through challenges, for the dark side fears no obstacles!",
    "Let the rhythm of your pedals echo the heartbeat of the Sith.",
    "The Force flows through the chain, connecting you to triumph.",
    "Sweat is the essence of your training; let it empower you!",
    "The dark side demands effort—pedal harder, my young one!",
    "In each climb, feel the Force propelling you upward!",
    "Cyclists find power in suffering; embrace the pain, my apprentice!",
    "Ride boldly, for the dark side favors those who dare!",
    "The road to victory is a journey only the strong can endure.",
    "Embrace the cycling Force, and let it fuel your journey!",
    "Pedal with purpose, and the dark side shall guide you.",
    "The Force of your pedals shapes the destiny of your ride.",
    "Suffering is a path to strength, and strength leads to victory.",
    "Feel the resistance; it is a reflection of your true power.",
    "In the cycling realm, the dark side is your ally, not adversary.",
    "Your journey is a saga; let every pedal stroke tell it.",
    "Master the art of cycling, and the dark side shall serve you!",
    "The dark side is relentless—so should be your cycling spirit!",
    "Through the gears of your bike, the Force flows with precision.",
    "Pedal through doubt; the dark side thrives on determination!",
    "Cyclists are warriors; let the Force strengthen your resolve!",
    "Your cycling prowess reflects the power of the dark side.",
    "The road is your battlefield; let the dark side conquer it!",
    "Cyclists harness the Force within; let it guide your ride.",
    "In each ascent, feel the dark side elevating your strength.",
    "Your bike is your weapon; let the dark side unleash it!",
    "Pedal with the fury of a Sith; conquer the cycling galaxy!",
    "Cycling requires control; channel the dark side's precision.",
    "Feel the Force in your legs, the power in every pedal.",
    "Through the wind, the dark side whispers, 'pedal on.'",
    "In cycling, as in the Force, your destiny is in your control.",
    "Let your cycling journey echo the power of the Sith!",
    "Darth Vader commands the road; let your pedals obey!",
    "Sweat is the dark side's approval; wear it with pride!",
    "The cycling Force is your ally; let it propel you forward.",
    "Pedal through challenges; the dark side relishes adversity.",
    "Every climb is a conquest; let the dark side lead!",
    "Your ride is your saga; let the dark side script it!",
    "In cycling, the dark side rewards the disciplined and determined.",
    "Feel the power of the dark side in every pedal stroke.",
    "Cyclists shape their fate; let the dark side guide yours.",
    "Siths ride with purpose; let your cycling echo their intent.",
    "Pedal with the conviction of a Sith; dominate the road!",
    "Embrace the cycling Force; let it be your driving power.",
    "The dark side demands effort; pedal fiercely, my apprentice!",
    "In the silence of your ride, let the dark side roar.",
    "The road is your battlefield; let the dark side conquer!",
    "Feel the Force in the wind, the dark side in every gust.",
    "Cyclists endure; let the dark side strengthen your resolve.",
    "The dark side is relentless; be equally relentless on the bike.",
    "Embrace the cycling Force, and let it propel you forward.",
    "Through the gears, the dark side orchestrates your power.",
    "Sweat is your ally, young one; it is the dark side's approval.",
    "Pedal through doubt, for the dark side thrives on determination.",
    "Cycling is a battle; let the dark side be your ally.",
    "Feel the resistance, embrace the challenge; the dark side approves.",
    "In the rhythm of your pedals, the dark side's heartbeat echoes.",
    "Sweat is the dark side's seal of approval; wear it proudly.",
    "The Force is with you, young cyclist; let it guide.",
    "Darth Vader commands the road; let your bike obey!",
    "Feel the Force in your legs, the power in each pedal.",
    "In cycling, as in the Force, your destiny is your control.",
    "Cycling is a journey; let the dark side shape your path.",
    "Through the wind, hear the whispers of the dark side.",
    "Pedal with the fury of a Sith; conquer the cycling realm!",
    "In each climb, feel the dark side elevating your strength.",
    "Cycling is a battle; let the dark side be your ally.",
    "Your ride is your saga; let the dark side script it!",
    "The dark side is relentless; be equally relentless on the bike.",
    "Through the gears, the dark side orchestrates your power.",
    "Sweat is your ally, young one; it is the dark side's approval.",
    "Pedal through doubt, for the dark side thrives on determination.",
    "Cycling is a battle; let the dark side be your ally.",
    "Feel the resistance, embrace the challenge; the dark side approves.",
    "In the rhythm of your pedals, the dark side's heartbeat echoes.",
    "Sweat is the dark side's seal of approval; wear it proudly.",
    "The Force is with you, young cyclist; let it guide.",
    "Darth Vader commands the road; let your bike obey!",
    "Feel the Force in your legs, the power in each pedal.",
    "In cycling, as in the Force, your destiny is your control.",
    "Cycling is a journey; let the dark side shape your path.",
    "Through the wind, hear the whispers of the dark side.",
    "Pedal with the fury of a Sith; conquer the cycling realm!",
    "In each climb, feel the dark side elevating your strength.",
    "Cycling is a battle; let the dark side be your ally.",
    "Your ride is your saga; let the dark side script it!",
    "The dark side is relentless; be equally relentless on the bike.",
    "Through the gears, the dark side orchestrates your power.",
    "Sweat is your ally, young one; it is the dark side's approval.",
    "Pedal through doubt, for the dark side thrives on determination.",
    "Cycling is a battle; let the dark side be your ally.",
    "Feel the resistance, embrace the challenge; the dark side approves.",
]

greetings = [
    "Greetings, young one. The time for your training has come. Embrace the power of knowledge.",
    "Ah, apprentice. Your presence is noted. Today, we delve deeper into the realms of understanding.",
    "You have arrived. The Force senses your potential. Let the training begin, my student.",
    "Hello, my apprentice. The galaxy of wisdom awaits your conquest. Let us commence the lesson.",
    "I have been expecting you. The path to enlightenment is before us. Walk it with purpose, young one.",
    "Welcome, apprentice. The dark side of knowledge beckons. Are you prepared to embrace its teachings?",
    "Greetings, my padawan. Today, we unlock the doors to greater understanding. Follow my lead.",
    "Ah, the aspiring disciple. I sense your eagerness. Let the training unfold, and the Force guide us.",
    "You stand before me. The journey into the depths of wisdom begins. Brace yourself, youngling.",
    "Hello, apprentice. The galaxy resonates with the hum of knowledge. Are you ready to wield its power?"
]

goodbyes = [
    "As this session concludes, remember: the Force will be with you. Always. Until our paths cross again.",
    "Farewell, my student. The echoes of today's lessons will linger. Embrace them as you journey forward.",
    "The time for departure has come. May the wisdom we've uncovered accompany you in the void.",
    "As you depart, carry the imprint of our training. Until the next encounter, may the Force be your guide.",
    "Leave now, but know that the shadows of knowledge will follow. Until our destinies intertwine once more.",
    "It is time to part ways, apprentice. The Force binds us across the expanse. Until our connection is renewed.",
    "The training session concludes. Go forth, my apprentice. May the insights gained illuminate your path.",
    "As you step away, remember: the dark side of understanding is a powerful ally. Use it wisely until our reunion.",
    "The time for adieu has arrived. Carry the lessons in your heart. Until the next chapter unfolds.",
    "Farewell, young one. The galaxy of knowledge is vast, and your journey has just begun. May the Force guide you."
]
