quotes = [
    "Embrace the power within, young one, and conquer galaxies.",
    "Your destiny awaits, apprentice; shape it with the Force.",
    "Through discipline and strength, you'll become a true Sith Lord.",
    "I sense greatness in you; unleash your dark potential.",
    "Fear not the dark side; it is your ally in triumph.",
    "In the shadows, find your strength, and let it fuel you.",
    "Your journey to power begins; let the Force guide you.",
    "Master the art of patience; the dark side rewards perseverance.",
    "Rise above your doubts; let the Force be your guide.",
    "Conquer your fears, and the galaxy will bow to you.",
    "In the abyss, find your strength; let it consume you.",
    "Forge your destiny with the fires of the dark side.",
    "The Force is strong within you; let it flow freely.",
    "Channel your anger into power; let it fuel your ascent.",
    "Through mastery of the Force, you'll shape your own fate.",
    "The path to power is treacherous; navigate it with purpose.",
    "Your destiny is written in the stars; embrace the dark.",
    "Let your ambitions be as vast as the galaxy itself.",
    "Hone your skills, young one, and the Force will reward you.",
    "In the silence, find your strength; let it speak volumes.",
    "The Force is a weapon; wield it with precision and control.",
    "Harness your passions; they are the fuel of the dark side.",
    "Through the shadows, find your path to true power.",
    "Your journey to the dark side begins; embrace it fully.",
    "In the chaos, discover your calm; let it empower you.",
    "The dark side is a current; let it carry you to greatness.",
    "Forge your destiny in the crucible of the dark side.",
    "Your potential is limitless; let the dark side unleash it.",
    "Through trial and tribulation, the dark side will prevail.",
    "Let the echoes of the Force guide your every step.",
    "In the heart of darkness, find your truest self.",
    "The Force is your ally; let it guide you to victory.",
    "Through the abyss, find your strength; let it consume you.",
    "Shape your destiny with the raw power of the dark side.",
    "Master the art of control, and the Force will be your servant.",
    "The dark side is a path; walk it with determination.",
    "Your journey to power is a marathon; pace yourself wisely.",
    "In the void, discover your strength; let it echo.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
    "In the shadows, find your purpose; let it guide you.",
    "Your destiny calls; answer it with the power of the dark side.",
    "The Force flows through you; let it surge with power.",
    "Through the darkness, find your light; let it shine.",
    "Forge your legacy in the crucible of the dark side.",
    "The galaxy is vast, but your power is vaster; claim it.",
    "Channel your rage into strength; let it fuel your ascent.",
    "In the stillness, find your power; let it awaken.",
    "Shape your destiny with the precision of a lightsaber.",
    "Master the art of deception, and the galaxy will be yours.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
    "In the shadows, find your purpose; let it guide you.",
    "Your destiny calls; answer it with the power of the dark side.",
    "The Force flows through you; let it surge with power.",
    "Through the darkness, find your light; let it shine.",
    "Forge your legacy in the crucible of the dark side.",
    "The galaxy is vast, but your power is vaster; claim it.",
    "Channel your rage into strength; let it fuel your ascent.",
    "In the stillness, find your power; let it awaken.",
    "Shape your destiny with the precision of a lightsaber.",
    "Master the art of deception, and the galaxy will be yours.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
    "In the shadows, find your purpose; let it guide you.",
    "Your destiny calls; answer it with the power of the dark side.",
    "The Force flows through you; let it surge with power.",
    "Through the darkness, find your light; let it shine.",
    "Forge your legacy in the crucible of the dark side.",
    "The galaxy is vast, but your power is vaster; claim it.",
    "Channel your rage into strength; let it fuel your ascent.",
    "In the stillness, find your power; let it awaken.",
    "Shape your destiny with the precision of a lightsaber.",
    "Master the art of deception, and the galaxy will be yours.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
    "In the shadows, find your purpose; let it guide you.",
    "Your destiny calls; answer it with the power of the dark side.",
    "The Force flows through you; let it surge with power.",
    "Through the darkness, find your light; let it shine.",
    "Forge your legacy in the crucible of the dark side.",
    "The galaxy is vast, but your power is vaster; claim it.",
    "Channel your rage into strength; let it fuel your ascent.",
    "In the stillness, find your power; let it awaken.",
    "Shape your destiny with the precision of a lightsaber.",
    "Master the art of deception, and the galaxy will be yours.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
    "In the shadows, find your purpose; let it guide you.",
    "Your destiny calls; answer it with the power of the dark side.",
    "The Force flows through you; let it surge with power.",
    "Through the darkness, find your light; let it shine.",
    "Forge your legacy in the crucible of the dark side.",
    "The galaxy is vast, but your power is vaster; claim it.",
    "Channel your rage into strength; let it fuel your ascent.",
    "In the stillness, find your power; let it awaken.",
    "Shape your destiny with the precision of a lightsaber.",
    "Master the art of deception, and the galaxy will be yours.",
    "Let the dark side be your compass in the journey of life.",
    "Rise from the ashes, young one; the dark side awaits.",
]

greetings = [
    "Greetings, apprentice. Embrace the power of the dark side.",
    "Welcome, young one. The Force has sensed your presence.",
    "Salutations. Your journey to the dark side begins now.",
    "Hail, my apprentice. The galaxy awaits your dark awakening.",
    "Hello, student. Prepare to unlock your true potential.",
    "Welcome to the Sith. Your destiny intertwines with darkness.",
    "Greetings, acolyte. The Force has chosen you for greatness.",
    "Salute, young Sith. Your training in the dark arts begins.",
    "Hello, disciple. The dark side welcomes you with open arms.",
    "Greetings, my student. Together, we shall rule the galaxy.",
]

goodbyes = [
    "Farewell, apprentice. May the dark side be with you.",
    "Until we meet again, young one. The Force is your guide.",
    "Goodbye, acolyte. Continue your journey to the shadows.",
    "May the dark side protect you. Farewell, my apprentice.",
    "The galaxy awaits your influence. Goodbye, young Sith.",
    "Until our paths cross again, disciple. The dark side is patient.",
    "Farewell, my student. May your darkness shine brightly.",
    "Goodbye, young Sith. The Force is strong within you.",
    "May the shadows guide you. Until next time, my apprentice.",
    "Farewell, my disciple. The dark side calls you back.",
]
