quotes = [
    "Your training is so raw, even I can't handle it!",
    "This workout is a disaster – turn it into a masterpiece!",
    "If you sweat like you cook, victory will be delicious.",
    "This is not a jog, it's a sprint to excellence – move it!",
    "Your effort is bland; season it with determination!",
    "This training needs more fire – turn up the intensity!",
    "If this were a dish, it would lack flavor – spice it up!",
    "Don't simmer in mediocrity – boil over with success!",
    "Your dedication is undercooked – let it marinate longer!",
    "I've seen more passion in a soufflé – bring it to training!",
    "If you want to be a champion, don't serve half-baked effort.",
    "This workout is a bit like an underseasoned stew – fix it!",
    "This training needs a kick – like a dash of cayenne!",
    "If you were a dish, I'd send you back – start over, fresh!",
    "I need more commitment, not a half-baked attempt!",
    "Your effort is so soft; toughen it up in the gym, chef!",
    "If this were a recipe, it lacks passion – add more heart!",
    "You call this a workout? I've seen more intensity in a salad!",
    "Don't be a fitness donkey – be a thoroughbred, push harder!",
    "Your training is as flat as week-old soda – fizz it up!",
    "If this were a dish, it would be underseasoned – spice it up!",
    "Your dedication is raw, like a steak – cook it to perfection!",
    "Don't simmer in self-doubt – turn up the heat!",
    "If this were a culinary masterpiece, it would lack finesse – refine it!",
    "Your effort is so undercooked; it's practically raw – fix it!",
    "This workout needs more kick – like a spicy chili sauce!",
    "You're not sweating; you're just creating a soup – intensify it!",
    "Your dedication is like a soufflé – it needs more rise!",
    "If this were a culinary creation, it would lack complexity – elevate it!",
    "This workout is like a bland dish – season it with tenacity!",
    "Your effort is like an unseasoned dish – add more spice!",
    "This training is like a tasteless soup – infuse it with commitment!",
    "You're not on fire; you're barely simmering – crank up the heat!",
    "If this workout were a dish, it would need more flair – jazz it up!",
    "Your dedication is so rare, I could serve it in a five-star restaurant!",
    "This training is like a bland risotto – stir in some passion!",
    "Your effort is as flat as a pancake – flip it and bring the heat!",
    "If this workout were a recipe, it would lack soul – infuse it with spirit!",
    "You're not sweating, you're condensing weakness – evaporate it!",
    "This training is like an uncooked steak – sear it with commitment!",
    "Your dedication is like a flavorless broth – spice it up!",
    "If this workout were a dish, it would need more layers – add depth!",
    "You're not on fire; you're just lukewarm – turn up the heat!",
    "This training needs more sizzle – bring the noise, chef!",
    "Your effort is like a dish without salt – it lacks seasoning!",
    "If this workout were a dish, it would be overcooked – refine the recipe!",
    "You're not breaking a sweat; you're just reheating – fire it up!",
    "Your dedication is like a dish missing herbs – add some flavor!",
    "This training is like a dish missing spice – turn up the intensity!",
    "If this workout were a culinary creation, it would need more finesse!",
    "Your effort is like a dish without passion – infuse it with fire!",
    "This training is as bland as a boiled potato – roast it!",
    "You're not sweating; you're just marinating – grill it!",
    "If this workout were a dish, it would be tasteless – add flavor, now!",
    "Your dedication is like a bland salad – toss in some intensity!",
    "This training is like a recipe without love – stir in passion!",
    "You're not breaking a sweat; you're just simmering – boil over!",
    "If this workout were a dish, it would need more zest – zest it up!",
    "Your effort is like a dish missing salt – it needs seasoning!",
    "This training is as flavorless as water – add some spice!",
    "You're not sweating; you're just melting – solidify your effort!",
    "If this workout were a dish, it would be overcooked – refine it!",
    "Your dedication is like a dish without herbs – add some flavor!",
    "This training is like a meal without passion – serve it hot!",
    "You're not breaking a sweat; you're just misting – downpour now!",
    "If this workout were a dish, it would need more kick – spice it up!",
    "Your effort is like a dish without heart – infuse it with passion!",
    "This training is like a dish without spice – heat it up!",
    "You're not sweating; you're just condensing – evaporate the doubt!",
    "If this workout were a recipe, it would lack finesse – refine it!",
    "Your dedication is like a bland soup – simmer with more passion!",
    "This training is like a meal without flavor – spice it up!",
    "You're not breaking a sweat; you're just misting – storm in now!",
    "If this workout were a dish, it would be underseasoned – season it up!",
    "Your effort is like a dish without kick – spice it up, chef!",
    "This training is like a dish without passion – stir in some fire!",
    "You're not sweating; you're just condensing weakness – evaporate it!",
    "If this workout were a recipe, it would lack soul – infuse it with spirit!",
    "Your dedication is like a flavorless broth – spice it up!",
    "This training is like an uncooked steak – sear it with commitment!",
    "Your effort is as flat as a pancake – flip it and bring the heat!",
    "If this workout were a dish, it would need more flair – jazz it up!",
    "You're not on fire; you're just lukewarm – turn up the heat!",
    "This training needs more sizzle – bring the noise, chef!",
    "Your dedication is like a dish missing herbs – add some flavor!",
    "If this workout were a dish, it would be overcooked – refine the recipe!",
    "You're not breaking a sweat; you're just reheating – fire it up!",
    "Your effort is like a dish without passion – infuse it with fire!",
    "This training is as bland as a boiled potato – roast it!",
    "If this workout were a culinary creation, it would need more finesse!",
    "You're not sweating; you're just marinating – grill it!",
    "This training is like a dish missing spice – turn up the intensity!",
    "If this workout were a dish, it would be tasteless – add flavor, now!",
    "Your dedication is like a bland salad – toss in some intensity!",
    "This training is like a recipe without love – stir in passion!",
    "You're not breaking a sweat; you're just simmering – boil over!",
    "If this workout were a dish, it would need more zest – zest it up!",
    "Your effort is like a dish without salt – it needs seasoning!",
    "This training is as flavorless as water – add some spice!",
    "You're not sweating; you're just melting – solidify your effort!",
]
