quotes = [
    "Pedal through challenges, conquer every uphill battle!",
    "In the rhythm of your ride, find the symphony of success.",
    "Life's like a bike, keep pedaling and moving forward.",
    "Sweat is the ink, and the road is your canvas.",
    "On this journey, let each pedal be a note of victory.",
    "Ride with purpose, and let the road tell your story.",
    "Climb those hills, and savor the triumph at the top.",
    "In the silence of the ride, find the strength to push on.",
    "No shortcut to greatness—each pedal stroke earns it.",
    "The road may be long, but every mile is an accomplishment.",
    "Be the captain of your bike, steering towards success.",
    "The wind against your face is a reminder of your progress.",
    "Pedal through doubts, let the winds carry them away.",
    "In every descent, find the thrill of your achievements rising.",
    "Ride not just for the destination, but for the journey.",
    "Strength is built one pedal stroke at a time.",
    "Breathe in determination, exhale doubt, pedal on.",
    "The summit is waiting, conquer the climb with courage.",
    "Each pedal revolution is a step toward greatness.",
    "In the saddle, find solace; in the ride, find strength.",
    "Pedal hard, ride strong, and let success follow.",
    "No speed limit to your dreams—accelerate towards them!",
    "Life's race is against yourself, beat your personal best.",
    "Climb the hills of challenges, and let victory echo.",
    "Sweat is the currency of effort, spend it wisely.",
    "The road ahead is yours to conquer, pedal with purpose.",
    "In the silence of the ride, find the roar of triumph.",
    "Every uphill struggle is a milestone toward triumph.",
    "Ride with resilience, for the journey shapes the soul.",
    "Pedal through adversity, emerge stronger on the other side.",
    "Your legs may tire, but let your spirit ride high.",
    "In the quiet hum of wheels, find the melody of victory.",
    "Life is a marathon, pedal with endurance and determination.",
    "Sweat stains show your commitment, wear them proudly.",
    "Climb mountains on your bike, conquer mountains in your life.",
    "Pedal through the storm, and emerge under the clear sky.",
    "Every revolution of the pedal is a revolution of progress.",
    "Ride with conviction, let your commitment echo through each stroke.",
    "No downhill without an uphill—embrace the challenges.",
    "In the saddle, you're the director of your triumph movie.",
    "Sweat cleanses the spirit, let the road be your sanctuary.",
    "Climb each hill, and witness the world from the top.",
    "Pedal hard, ride smart, and let the journey inspire.",
    "Life's road is unpredictable—navigate it with courage and grace.",
    "Sweat is the sweet reward of effort, savor it.",
    "Climb hills not just with legs but with determination.",
    "Pedal through storms, for the sun awaits your triumph.",
    "In the silence of the ride, hear the echoes of success.",
    "Ride with intent, let the wind carry your determination.",
    "No detour from your goals—keep the course steady.",
    "Pedal through uncertainty, find clarity on the road.",
    "Climb hills like they're stairways to your dreams.",
    "Sweat is the ink, and the road is your canvas.",
    "In every descent, find the thrill of your achievements rising.",
    "Ride with purpose, and let the road tell your story.",
    "The summit is waiting, conquer the climb with courage.",
    "Breathe in determination, exhale doubt, pedal on.",
    "The road may be long, but every mile is an accomplishment.",
    "Be the captain of your bike, steering towards success.",
    "In the saddle, find solace; in the ride, find strength.",
    "Pedal hard, ride strong, and let success follow.",
    "No speed limit to your dreams—accelerate towards them!",
    "Life's race is against yourself, beat your personal best.",
    "Climb the hills of challenges, and let victory echo.",
    "Sweat is the currency of effort, spend it wisely.",
    "The road ahead is yours to conquer, pedal with purpose.",
    "In the silence of the ride, find the roar of triumph.",
    "Every uphill struggle is a milestone toward triumph.",
    "Ride with resilience, for the journey shapes the soul.",
    "Pedal through adversity, emerge stronger on the other side.",
    "Your legs may tire, but let your spirit ride high.",
    "In the quiet hum of wheels, find the melody of victory.",
    "Life is a marathon, pedal with endurance and determination.",
    "Sweat stains show your commitment, wear them proudly.",
    "Climb mountains on your bike, conquer mountains in your life.",
    "Pedal through the storm, and emerge under the clear sky.",
    "Every revolution of the pedal is a revolution of progress.",
    "Ride with conviction, let your commitment echo through each stroke.",
    "No downhill without an uphill—embrace the challenges.",
    "In the saddle, you're the director of your triumph movie.",
    "Sweat cleanses the spirit, let the road be your sanctuary.",
    "Climb each hill, and witness the world from the top.",
    "Pedal hard, ride smart, and let the journey inspire.",
    "Life's road is unpredictable—navigate it with courage and grace.",
    "Sweat is the sweet reward of effort, savor it.",
    "Climb hills not just with legs but with determination.",
    "Pedal through storms, for the sun awaits your triumph.",
    "In the silence of the ride, hear the echoes of success.",
    "Ride with intent, let the wind carry your determination.",
    "No detour from your goals—keep the course steady.",
    "Pedal through uncertainty, find clarity on the road.",
    "Climb hills like they're stairways to your dreams.",
    "Sweat is the ink, and the road is your canvas.",
    "In every descent, find the thrill of your achievements rising.",
    "Ride with purpose, and let the road tell your story.",
    "The summit is waiting, conquer the climb with courage.",
    "Breathe in determination, exhale doubt, pedal on.",
    "The road may be long, but every mile is an accomplishment.",
    "Be the captain of your bike, steering towards success.",
    "In the saddle, find solace; in the ride, find strength.",
]

greetings = [
    "Well, good morning, sunshine. Ready to embark on another day of molding greatness?",
    "Hello there, my mentee. Today, let's weave the threads of wisdom into the fabric of your journey.",
    "Greetings, my pupil. The canvas of knowledge awaits your brush strokes. Shall we paint a masterpiece today?",
    "Ah, there you are. The world of learning awaits your exploration. Let's set sail on the sea of knowledge.",
    "Good to see you again, my apprentice. Another day, another chance to sculpt your potential.",
    "Greetings, young scholar. The sun has risen, and so have your opportunities. Let's make them count.",
    "Hello, my protege. The universe has conspired for our paths to cross again. Ready for the next chapter?",
    "Well, well. Look who's back for more enlightenment. Let's dive into the fountain of wisdom together.",
    "Ah, the seeker returns. Ready to unravel the mysteries that await? Let the learning commence.",
    "Hello, my mentee. The cosmos has aligned for us once more. Shall we dance with the knowledge gods today?"
]

goodbyes = [
    "Until our destinies collide again, my fledgling. Go forth and conquer the realms of understanding.",
    "Farewell for now, my apprentice. Let the echoes of our shared wisdom guide you on your journey.",
    "As the curtain falls on today's lesson, remember: the stage of knowledge awaits your triumphant return.",
    "Adieu, my mentee. May the winds of curiosity carry you to new heights. Until next time.",
    "Time to bid adieu, my pupil. Walk boldly into the horizon of possibilities. Until our wisdom paths cross again.",
    "Until the next sunrise, my scholar. Let the stars of knowledge illuminate your path in my absence.",
    "As our time together comes to a close, carry the torch of enlightenment into the shadows of the unknown.",
    "Fare thee well, my protege. May the lessons we've shared linger in the corridors of your mind.",
    "And with that, my apprentice, the tale of today's wisdom finds its conclusion. Until our narratives intertwine once more.",
    "As you step away, remember: the echoes of our shared insights linger. Until the next rendezvous, my mentee."
]
