quotes = ["In the arena, sculpt your destiny with unwavering determination.",
          "On this field of dreams, sow the seeds of your triumph.",
          "Aim for the stars, for you are destined for greatness.",
          "In the symphony of effort, play the chords of resilience.",
          "Your journey echoes with the footsteps of champions past.",
          "Each drop of sweat narrates a tale of relentless pursuit.",
          "Embrace the challenge – it's the heartbeat of champions.",
          "Forge your character in the fires of dedication and discipline.",
          "In the theater of competition, be the lead actor of success.",
          "Write your legacy with the pen of relentless perseverance.",
          "On this canvas of ambition, paint strokes of victory.",
          "You are the author of your story – script triumph.",
          "Let the rhythm of dedication guide your every move.",
          "Champion the cause of your dreams with indomitable spirit.",
          "Your path is paved with the bricks of hard-earned success.",
          "In the arena, rise like a phoenix from the ashes.",
          "Craft your success with the hands of relentless toil.",
          "The stage is set – perform the masterpiece of victory.",
          "Every step forward is a verse in the ballad of triumph.",
          "In the tapestry of effort, weave threads of glory.",
          "Elevate your game – let excellence be your language.",
          "In the arena of dreams, orchestrate your own symphony.",
          "Dance with destiny on the grand stage of your goals.",
          "Your sweat is the ink that writes the scrolls of success.",
          "Conquer the marathon of dreams with strides of persistence.",
          "In the grand theater of life, star in your own epic.",
          "The journey is the destination – savor each step.",
          "On the canvas of achievement, paint strokes of resilience.",
          "Be the conductor of your fate – orchestrate victory.",
          "In the mosaic of effort, each piece contributes to triumph.",
          "As the protagonist of your story, script success chapters.",
          "The journey molds the champion – embrace the process.",
          "Carve your legacy with the chisel of dedication.",
          "In the realm of dreams, wield the sword of determination.",
          "Every stride forward echoes in the halls of triumph.",
          "Champion the cause of your dreams with steadfast resolve.",
          "Your destiny unfolds with the turning pages of effort.",
          "Navigate the seas of challenges with the compass of courage.",
          "Your journey is a sonnet of perseverance and victory.",
          "On the stage of ambition, perform the dance of excellence.",
          "In the symphony of success, let your spirit be the melody.",
          "Write your story with the pen of unwavering commitment.",
          "Your effort is the heartbeat of the champion within.",
          "On the canvas of dreams, sketch the masterpiece of success.",
          "The tapestry of triumph is woven with threads of resilience.",
          "Champion the cause of excellence with relentless dedication.",
          "In the theater of life, be the director of your destiny.",
          "Sculpt your success with the hands of unyielding effort.",
          "Every step forward is a note in the melody of victory.",
          "In the arena of dreams, manifest your own legend.",
          "Craft your legacy with the tools of determination and grit.",
          "On the canvas of ambition, paint the strokes of success.",
          "Champion the cause of your dreams with tenacity.",
          "In the tapestry of effort, weave the fabric of triumph.",
          "Your journey is the poem that echoes with triumph.",
          "Elevate your game – let excellence be your anthem.",
          "In the grand theater of life, star in your own drama.",
          "Every step forward is a brushstroke in the mural of victory.",
          "Write your story with the pen of unwavering resolve.",
          "The journey is the destination – savor each moment.",
          "On the canvas of dreams, sketch the masterpiece of success.",
          "Conduct the symphony of your success with grace.",
          "Your journey is the novel that unfolds with triumph.",
          "In the mosaic of effort, each piece contributes to success.",
          "Champion the cause of your dreams with steadfast resolve.",
          "Navigate the seas of challenges with the compass of courage.",
          "Your destiny unfolds with the turning pages of effort.",
          "Craft your legacy with the chisel of dedication.",
          "In the realm of dreams, wield the sword of determination.",
          "Every stride forward echoes in the halls of triumph.",
          "Champion the cause of your dreams with relentless dedication.",
          "Your journey is a sonnet of perseverance and victory.",
          "On the stage of ambition, perform the dance of excellence.",
          "Write your story with the pen of unwavering commitment.",
          "Your effort is the heartbeat of the champion within.",
          "On the canvas of dreams, sketch the masterpiece of success.",
          "The tapestry of triumph is woven with threads of resilience.",
          "Champion the cause of excellence with relentless dedication.",
          "In the theater of life, be the director of your destiny.",
          "Sculpt your success with the hands of unyielding effort.",
          "Every step forward is a note in the melody of victory.",
          "In the arena of dreams, manifest your own legend.",
          "Craft your legacy with the tools of determination and grit.",
          "On the canvas of ambition, paint the strokes of success.",
          "Champion the cause of your dreams with tenacity.",
          "In the tapestry of effort, weave the fabric of triumph.",
          "Your journey is the poem that echoes with triumph.",
          "Elevate your game – let excellence be your anthem.",
          "In the grand theater of life, star in your own drama.",
          "Every step forward is a brushstroke in the mural of victory.",
          "Write your story with the pen of unwavering resolve.",
          "The journey is the destination – savor each moment.",
          "On the canvas of dreams, sketch the masterpiece of success.",
          "Conduct the symphony of your success with grace.",
          "Your journey is the novel that unfolds with triumph.",
          "In the mosaic of effort, each piece contributes to success.",
          "Champion the cause of your dreams with steadfast resolve.",
          "Navigate the seas of challenges with the compass of courage.",
          "Your destiny unfolds with the turning pages of effort.",
          "Craft your legacy with the chisel of dedication."]
