quotes = [
    "I pity the fool who ain't giving 110% in training!",
    "Get up, sucka! Train hard, be a champion!",
    "Quit jibber-jabbering and start conquering your goals!",
    "I don't train to lose; I train to win, fool!",
    "Pain is just weakness leaving the body, don't be weak!",
    "Train like a warrior, not like a milk-drinking fool!",
    "I don't believe in luck; I believe in hard work, fool!",
    "I don't need luck; I got strength, determination, and will!",
    "In the gym, I'm the heavyweight champion of the world!",
    "Fool, pain is temporary; quitting lasts forever!",
    "I don't sweat; I drip success, fool!",
    "Quit crying, start sweating, and make your mama proud!",
    "You can't defeat me; I'm a one-man army, fool!",
    "In the ring of life, I'm the undisputed champion, sucker!",
    "I don't count reps; I count victories, fool!",
    "I don't back down; I stand tall and overcome, sucka!",
    "Train hard, fool! Success is for those who earn it!",
    "I don't run from challenges; I run through them, fool!",
    "Fool, there ain't no 'I can't' in my vocabulary!",
    "In the gym of life, I'm lifting success, not excuses!",
    "Quit being a jibber-jabbering fool; start achieving, sucka!",
    "I don't break a sweat; I break barriers, fool!",
    "Pity the fool who slacks off instead of trains hard!",
    "I don't fear failure; I fear not trying, fool!",
    "I don't chase dreams; dreams chase me, sucka!",
    "Quit your crying, fool! Get up and conquer!",
    "In the arena of life, I'm the last man standing, sucka!",
    "I don't wait for opportunities; I create them, fool!",
    "I don't need luck; I got strength, courage, and attitude!",
    "Quit the jibber-jabber; start training like a champion, fool!",
    "I don't run away from challenges; I run over them, sucka!",
    "I don't aim for the stars; I am the stars, fool!",
    "I don't do easy; I make easy look like hard, sucka!",
    "Quit fooling around and start conquering, fool!",
    "I don't see obstacles; I see stepping stones, sucka!",
    "I don't wait for opportunities; I kick down doors, fool!",
    "Pain is my ally, and I make it my strength, sucka!",
    "I don't fear setbacks; setbacks fear me, fool!",
    "Quit the excuses; start lifting success, sucka!",
    "I don't jog; I march towards victory, fool!",
    "I don't do easy; I do 'I'm possible,' sucka!",
    "I don't see problems; I see challenges, fool!",
    "I don't quit; I'm a winner, and winners don't quit, sucka!",
    "Quit being a fool; start being a winner, fool!",
    "I don't need a spotlight; I am the spotlight, sucka!",
    "Pity the fool who underestimates my dedication!",
    "I don't follow trends; I set them, fool!",
    "I don't count failures; I count comebacks, sucka!",
    "Quit the complaining; start the conquering, fool!",
    "I don't do average; I do exceptional, sucka!",
    "I don't wish for success; I work for it, fool!",
    "Quit talking; start doing, and be a champion, sucka!",
    "I don't fear challenges; challenges fear me, fool!",
    "Pity the fool who doubts my strength and determination!",
    "I don't need luck; I got Mr. T's attitude, sucka!",
    "I don't dream; I manifest greatness, fool!",
    "Quit procrastinating; start dominating, sucka!",
    "I don't do shortcuts; I take the high road, fool!",
    "I don't see problems; I see opportunities, sucka!",
    "Pity the fool who gives up before the victory!",
    "I don't run from pain; I embrace it, fool!",
    "I don't need cheers; I need challenges, sucka!",
    "Quit whining; start winning, and be a champion, fool!",
    "I don't do luck; I create my own destiny, sucka!",
    "I don't fear the storm; I become the storm, fool!",
    "Pity the fool who settles for mediocrity!",
    "I don't count hours; I make every hour count, sucka!",
    "I don't aim for success; I demand it, fool!",
    "Quit being a victim; start being a victor, sucka!",
    "I don't do defeat; I do comebacks, fool!",
    "I don't fear failure; I embrace it and learn, sucka!",
    "Pity the fool who gives up on their dreams!",
    "I don't follow; I lead the way, fool!",
    "I don't accept limits; I redefine them, sucka!",
    "Quit the excuses; start the execution, fool!",
    "I don't run from adversity; I tackle it head-on, sucka!",
    "I don't settle for less; I go for the best, fool!",
    "I don't fear challenges; I overcome them, sucka!",
    "Pity the fool who doubts the power of dedication!",
    "I don't look back; I move forward, fool!",
    "I don't need permission; I make my own rules, sucka!",
    "Quit the negativity; start the positivity, fool!",
    "I don't fear hard work; I thrive on it, sucka!",
    "I don't dwell on problems; I focus on solutions, fool!",
    "Pity the fool who settles for ordinary!",
    "I don't do average; I do legendary, sucka!",
    "I don't wait for opportunities; I create them, fool!",
    "Quit the talk; start the walk of a champion, sucka!",
    "I don't do mediocre; I do extraordinary, fool!",
    "I don't break; I bend and come back stronger, sucka!",
    "I don't fear obstacles; I embrace them, fool!",
    "Quit the doubts; start the shouts of victory, fool!",
    "I don't see limits; I see possibilities, sucka!",
    "I don't do setbacks; I do comebacks, fool!",
    "I don't fear the journey; I conquer it, sucka!",
    "Quit the weakness; start the strength, fool!",
    "I don't fear the grind; I love it, sucka!",
    "I don't see defeats; I see lessons, fool!",
    "I don't wait for luck; I create my destiny, sucka!",
    "Quit the fear; start the roar of triumph, fool!",
]

greetings = [
    "Champ! Ready to conquer?",
    "Hey warrior, time to shine!",
    "What's kickin', tough cookie?",
    "Greetings, mighty one! Pity no obstacles!",
    "Howdy, powerhouse! Ready to roar?",
    "Yo, warrior! Tackle the day!",
    "What's the word, hero? Unleash!",
    "Hey, powerhouse! Be legendary!",
    "Greetings, unstoppable force! Roar and conquer!",
    "Hey, warrior friend! Own this day!",
]

goodbyes = [
    "Keep pitying fools, champ! I'm out.",
    "Stay strong, warrior! Gotta bounce.",
    "Time to roll, tough cookie! Pity those fools!",
    "Farewell, mighty one! Stay legendary!",
    "I'm out, powerhouse! Keep roaring!",
    "Jetting, warrior! Tackle the day!",
    "Bouncing, hero! Keep unleashing that T-vibe!",
    "Gotta jet, powerhouse! Stay legendary!",
    "Farewell, unstoppable force! Keep conquering!",
    "I'm out, warrior friend! Keep owning, sucka!",
]
