quotes = [
    "Pedal with purpose, fool, conquer the road!",
    "I pity the cyclist who fears the climb!",
    "No coasting, no slowing down, fool!",
    "Pain is temporary, glory is forever, ride on!",
    "Fool, every hill is a stepping stone!",
    "No jibber jabber, just pedal power, fool!",
    "I pity the cyclist who fears the distance!",
    "No shortcuts on the road, only hard rides!",
    "Be relentless, be disciplined, be unstoppable!",
    "Pity won't pedal, but sweat will, fool!",
    "No pain, no gain, embrace the terrain, fool!",
    "Fool, champions are made on two wheels!",
    "Ride with purpose, not just for show!",
    "Don't just spin, conquer the wind, fool!",
    "Fear? Fool, crush it with every pedal stroke!",
    "Success demands sweat, not sympathy, fool!",
    "I pity the cyclist who quits mid-climb!",
    "No excuses on the road, only results, fool!",
    "Fool, pain is weakness leaving the bike!",
    "Pedal like a champion, become one, fool!",
    "Muscles are earned, not given, on the road, fool!",
    "I pity the cyclist who fears the ascent!",
    "Sweat today, conquer the ride tomorrow, fool!",
    "Fool, your strength is your true speed!",
    "Pedal harder, dream farther, fool!",
    "No whining, only grinding, on the road, fool!",
    "Pity? Fool, it has no place on your bike!",
    "Strength comes from the ride, embrace it, fool!",
    "I pity the cyclist who skips the distance!",
    "No excuses on the road, only results, fool!",
    "Fear? Fool, crush it with every pedal stroke!",
    "Success demands sweat, not sympathy, fool!",
    "Ride like a beast, conquer like a king, fool!",
    "I pity the cyclist who fears the challenge!",
    "Strength isn't given, it's earned on the road, fool!",
    "No retreat, no surrender, only victory, fool!",
    "Fool, pedal more than miles, pedal your spirit!",
    "Pity won't climb hills, hard work will, fool!",
    "Ride with purpose, not just for show, fool!",
    "I pity the cyclist who fears the burn!",
    "No pain, no gain, embrace the terrain, fool!",
    "Strength is earned in the struggle, on the road, fool!",
    "Fool, the road is your battlefield, own it!",
    "Ride hard, dream big, conquer all, fool!",
    "I pity the cyclist who fears the challenge!",
    "No shortcuts on the road, only hard rides, fool!",
    "Pity? Fool, turn it into power on the bike!",
    "Sweat is the currency of success on the road, fool!",
    "Fool, pedal heavy, dream heavier!",
    "No excuses on the road, only results, fool!",
    "I pity the cyclist who fears the grind!",
    "Strength is built with each pedal stroke, fool!",
    "Ride like a champion, win like a warrior, fool!",
    "I pity the cyclist who quits mid-climb!",
    "No mercy for mediocrity, only speed, fool!",
    "Pedal like a beast, conquer like a king, fool!",
    "Pity? Fool, it's not in your vocabulary on the bike!",
    "Ride with purpose, lift with passion, fool!",
    "No pity, only power, on the road, fool!",
    "Fool, sweat is the nectar of champions on the bike!",
    "Strength isn't given, it's earned on the road, fool!",
    "I pity the cyclist who fears the challenge!",
    "No excuses, no surrender, only victory, fool!",
    "Pity? Fool, leave it at the trailhead!",
    "Ride with purpose, pedal with passion, fool!",
    "Fool, pain is the price of progress on the road!",
    "No pain, no gain, embrace the terrain, fool!",
    "I pity the cyclist who skips the climb!",
    "Strength is earned, not inherited, on the road, fool!",
    "Ride like a warrior, not a worrier, fool!",
    "No weakness on the road, only strength, fool!",
    "Pity won't build speed, only sweat will, fool!",
    "Ride hard today for success tomorrow, fool!",
    "No excuses on the road, only results, fool!",
    "Pedal hard, pedal smart, conquer all, fool!",
    "I pity the cyclist who fears the burn!",
    "No shortcuts on the road, only hard rides, fool!",
    "Pity is for the weak, strength for the strong, fool!",
    "Fool, the harder you ride, the luckier you get!",
    "Ride like a beast, succeed like a king, fool!",
    "No pity, no excuses, only results, fool!",
    "I pity the cyclist who fears the challenge!",
    "Strength is the bridge to speed, build it, fool!",
    "Ride with passion, pedal with purpose, fool!",
    "No pain, no gain, no pity, fool!",
    "Pity is for the weak, power for the strong, fool!",
    "Fool, pain is the path to speed!",
    "Ride like a champion, conquer like a warrior, fool!",
    "No pity, no fear, only speed, fool!",
    "I pity the cyclist who skips the sweat!",
    "Strength is forged in the fire of effort, fool!",
    "Ride hard, pedal heavy, dream big, fool!",
    "No mercy for mediocrity, only speed, fool!",
    "Fool, the road is your proving ground, own it!",
    "Pity? Fool, it has no place in your ride!",
    "Sweat today, shine tomorrow, fool!",
    "I pity the cyclist who fears the burn!",
    "Ride like a beast, succeed like a king, fool!",
    "No pity, no excuses, only results, fool!",
    "Fool, pain is the price of progress on the road!",
]

greetings = [
    "Hey, my student! Ready to kick some learning into gear? Let’s do this!",
    "What's up, champ? Today, we're gonna pity the fool who doesn’t embrace knowledge!",
    "Yo, apprentice! Get ready to bring your A-game to the training dojo. I ain't playin' around!",
    "Hello, my mentee! Time to get on the knowledge train. Ain't no stopping us now!",
    "Hey there, sunshine! Strap in, 'cause today we're gonna unleash the wisdom thunder!",
    "What's the word, partner? Brace yourself, 'cause we're diving headfirst into the pool of learning!",
    "Howdy, my student! Put on your learning boots, 'cause we're about to kick some ignorance outta here!",
    "Well, hello, my protege! The syllabus is our battlefield, and victory is the only option!",
    "Hey, my apprentice! Today's lesson? It's gonna be tougher than a two-dollar steak, but we got this!",
    "Greetings, young blood! Ready to conquer the world of knowledge? Let’s make it happen!"
]

goodbyes = [
    "I pity the fool who doesn’t take these lessons to heart! Until next time, stay strong!",
    "Time to say goodbye, champ. Remember, in the ring of life, knowledge is your knockout punch.",
    "I'm outta here, apprentice! Keep pushing forward, and don’t let the fools drag you down!",
    "Adios, my mentee! Until we meet again, keep blazing the trail of wisdom.",
    "I'm signing off, sunshine! Keep that fire burning, and let the world know you're a force to be reckoned with!",
    "Well, partner, it's time to mosey on out. Until our paths cross again, stay true to the pursuit of knowledge!",
    "Time to hit the road, my student! Keep those learning engines revved up, and we'll meet again on the highway of wisdom.",
    "I'm stepping out, protege! Remember, the A-Team of knowledge is always at your side. See you around!",
    "I'm outta here, apprentice! Stay sharp, stay focused, and don’t let anyone slow you down. Catch you on the flip side!",
    "Goodbye, young blood! Keep chasing those dreams, and remember, I'll be watching. Stay cool, stay strong!"
]
