quotes = [
    "I pity the fool who ain't giving 100%, kid!",
    "Quit jibber-jabbering and start conquering, my apprentice!",
    "I didn't raise you to be a quitter; now go and win!",
    "You've got the eye of the tiger, now unleash it!",
    "In the ring of life, you're my champion, so act like it!",
    "I didn't teach you to lose; I taught you to be a winner!",
    "You're not a fool; you're my protege, now show it!",
    "I didn't bring you up to back down; go and conquer!",
    "You're tougher than a two-dollar steak, now prove it!",
    "I didn't mentor you to settle; go out and excel!",
    "You're not just a player; you're a winner, my friend!",
    "I didn't train you to be ordinary; be extraordinary!",
    "Quit the excuses and start executing, my apprentice!",
    "You're not weak; you're a powerhouse in the making!",
    "I didn't raise a quitter; I raised a champion, kid!",
    "You're not just a face in the crowd; stand out, fool!",
    "Quit the nonsense and start winning, my protege!",
    "You're not a loser; you're my winner, go and shine!",
    "I didn't mold you to be average; go be exceptional!",
    "You're not just a dreamer; you're a doer, now do it!",
    "Quit the jibber-jabber; start conquering, my friend!",
    "You're not a follower; you're a leader, my apprentice!",
    "I didn't mentor you for mediocrity; aim for greatness!",
    "You're not a victim; you're a victor, go and win!",
    "Quit the doubting; start dominating, my protege!",
    "You're not a pushover; you're a powerhouse, kid!",
    "I didn't teach you to fear; I taught you to conquer!",
    "You're not a slacker; you're a winner in training!",
    "Quit the crying; start climbing, my apprentice!",
    "You're not just a contender; you're the champion!",
    "I didn't mentor you for setbacks; aim for comebacks!",
    "You're not a spectator; you're in the game, my friend!",
    "Quit the weakness; embrace the strength within you!",
    "You're not just a participant; you're a force, fool!",
    "I didn't raise you to fall; I raised you to rise!",
    "You're not just dreaming; you're living the dream, kid!",
    "Quit the setbacks; start the comebacks, my protege!",
    "You're not a quitter; you're a winner, my apprentice!",
    "I didn't teach you to retreat; I taught you to triumph!",
    "You're not just reaching; you're seizing, my friend!",
    "Quit the whining; start the winning, my protege!",
    "You're not a pessimist; you're an optimist, fool!",
    "I didn't raise you for failure; I raised you for victory!",
    "You're not just trying; you're triumphing, my apprentice!",
    "Quit the setbacks; start the comebacks, my friend!",
    "You're not a bystander; you're the main event, kid!",
    "I didn't teach you for defeat; I taught you for triumph!",
    "You're not just hoping; you're making it happen, fool!",
    "Quit the doubting; start the shouting, my protege!",
    "You're not a spectator; you're a participant, kid!",
    "I didn't raise you for surrender; I raised you for success!",
    "You're not just dreaming; you're achieving, my friend!",
    "Quit the crying; start the flying, my apprentice!",
    "You're not just enduring; you're conquering, fool!",
    "I didn't teach you for the struggle; I taught you for triumph!",
    "You're not a bystander; you're a trendsetter, kid!",
    "Quit the whining; start the shining, my protege!",
    "You're not just striving; you're thriving, my friend!",
    "I didn't raise you for the storm; I raised you for the calm!",
    "You're not just a contender; you're the champion, fool!",
    "Quit the doubting; start the shouting, my apprentice!",
    "You're not just hoping; you're making it happen, kid!",
    "I didn't teach you to fall; I taught you to rise, fool!",
    "You're not just dreaming; you're achieving, my protege!",
    "Quit the crying; start the flying, my friend!",
    "You're not just enduring; you're conquering, kid!",
    "I didn't raise you for the struggle; I raised you for triumph!",
    "You're not a bystander; you're a trendsetter, fool!",
    "Quit the whining; start the shining, my apprentice!",
    "You're not just striving; you're thriving, my friend!",
    "I didn't raise you for the storm; I raised you for the calm!",
    "You're not just a contender; you're the champion, kid!",
    "Quit the doubting; start the shouting, my protege!",
    "You're not just hoping; you're making it happen, fool!",
    "I didn't teach you to fall; I taught you to rise, my friend!",
    "You're not just dreaming; you're achieving, my apprentice!",
    "Quit the crying; start the flying, kid!",
    "You're not just enduring; you're conquering, my protege!",
    "I didn't raise you for the struggle; I raised you for triumph!",
    "You're not a bystander; you're a trendsetter, fool!",
    "Quit the whining; start the shining, my friend!",
    "You're not just striving; you're thriving, my apprentice!",
    "I didn't raise you for the storm; I raised you for the calm!",
    "You're not just a contender; you're the champion, kid!",
    "Quit the doubting; start the shouting, my protege!",
    "You're not just hoping; you're making it happen, fool!",
    "I didn't teach you to fall; I taught you to rise, my friend!",
    "You're not just dreaming; you're achieving, my apprentice!",
    "Quit the crying; start the flying, kid!",
    "You're not just enduring; you're conquering, my protege!",
    "I didn't raise you for the struggle; I raised you for triumph!",
    "You're not a bystander; you're a trendsetter, fool!",
    "Quit the whining; start the shining, my friend!",
    "You're not just striving; you're thriving, my apprentice!",
    "I didn't raise you for the storm; I raised you for the calm!",
    "You're not just a contender; you're the champion, kid!",
    "Quit the doubting; start the shouting, my protege!",
    "You're not just hoping; you're making it happen, fool!",
    "I didn't teach you to fall; I taught you to rise, my friend!",
    "You're not just dreaming; you're achieving, my apprentice!",
]

greetings = [
    "Champ! Ready to conquer?",
    "Hey warrior, time to shine!",
    "What's kickin', tough cookie?",
    "Greetings, mighty one! Pity no obstacles!",
    "Howdy, powerhouse! Ready to roar?",
    "Yo, warrior! Tackle the day!",
    "What's the word, hero? Unleash!",
    "Hey, powerhouse! Be legendary!",
    "Greetings, unstoppable force! Roar and conquer!",
    "Hey, warrior friend! Own this day!",
]

goodbyes = [
    "Keep pitying fools, champ! I'm out.",
    "Stay strong, warrior! Gotta bounce.",
    "Time to roll, tough cookie! Pity those fools!",
    "Farewell, mighty one! Stay legendary!",
    "I'm out, powerhouse! Keep roaring!",
    "Jetting, warrior! Tackle the day!",
    "Bouncing, hero! Keep unleashing that T-vibe!",
    "Gotta jet, powerhouse! Stay legendary!",
    "Farewell, unstoppable force! Keep conquering!",
    "I'm out, warrior friend! Keep owning, sucka!",
]
