quotes = [
    "Saddle up, darling! Success is a wild ride!",
    "Life's a race, not a trot—pedal with purpose!",
    "No horsing around, just pedal power, honey!",
    "Gallop towards greatness, leave doubt in the dust!",
    "Don't be a neigh-sayer, be a go-getter, sweetie!",
    "Every pedal stroke propels you toward triumph!",
    "Strap in, pedal on, and gallop to victory!",
    "I've seen setbacks, but honey, you're no setback!",
    "Sweat like you mean it, darling, it's horsepower!",
    "Pedal through the pain, reap the victory, sweetheart!",
    "Life's a hill, climb it with grace and gusto!",
    "I've chased dreams, now chase yours, pedal by pedal!",
    "Don't trot when you can gallop, darling, go for it!",
    "No horsing around, just full-speed determination!",
    "Pedal harder, darling, the finish line is calling!",
    "Dream big, ride hard, and let success follow!",
    "Ride like the wind, sweetie, and leave doubt behind!",
    "Strive for the mane event, conquer the journey!",
    "Saddle up, sweetheart, and let ambition lead!",
    "Pedal like every revolution is a victory lap!",
    "No excuses, just pedal power and persistence!",
    "Every climb is a chance to reach new heights!",
    "I've tamed challenges, now it's your turn, honey!",
    "Sweat like you're chasing dreams, not just trails!",
    "Pedal with passion, darling, and own the road!",
    "Success is a journey, ride it with flair, sweetie!",
    "Gallop with gumption, darling, you've got this!",
    "Life's a race, darling, leave mediocrity behind!",
    "Climb every hill with the strength of a stallion!",
    "Don't trot when you can sprint, sweetie, go big!",
    "No horsing around, just full-throttle determination!",
    "Saddle up, sweetheart, and ride into greatness!",
    "Pedal like your dreams are waiting at the finish line!",
    "Life's a trail, blaze it with bold determination!",
    "Dream big, ride hard, and let success follow!",
    "Strive for the mane event, conquer the journey!",
    "Saddle up, sweetheart, and let ambition lead!",
    "Pedal like every revolution is a victory lap!",
    "No excuses, just pedal power and persistence!",
    "Every climb is a chance to reach new heights!",
    "I've tamed challenges, now it's your turn, honey!",
    "Sweat like you're chasing dreams, not just trails!",
    "Pedal with passion, darling, and own the road!",
    "Success is a journey, ride it with flair, sweetie!",
    "Gallop with gumption, darling, you've got this!",
    "Life's a race, darling, leave mediocrity behind!",
    "Climb every hill with the strength of a stallion!",
    "Don't trot when you can sprint, sweetie, go big!",
    "No horsing around, just full-throttle determination!",
    "Saddle up, sweetheart, and ride into greatness!",
    "Pedal like your dreams are waiting at the finish line!",
    "Life's a trail, blaze it with bold determination!",
    "Keep your eyes on the road, darling, not the hurdles!",
    "I've galloped through challenges, now it's your turn!",
    "Pedal through the pain, darling, it's just a detour!",
    "Don't just ride, lead the stampede, sweetheart!",
    "Every pedal stroke is a step toward victory, honey!",
    "No horsing around, just relentless pursuit, darling!",
    "Sweat like success is chasing you, not the other way!",
    "Pedal with poise, sweetie, and let confidence ride!",
    "Life's a track, race it with tenacity and grace!",
    "Climb hills like they're stairs to your dreams, darling!",
    "I've navigated the course, now it's your time to shine!",
    "Don't trot when you can canter, sweetheart, go faster!",
    "Saddle up, honey, and ride toward your horizon!",
    "Pedal like you're in pursuit of your wildest dreams!",
    "Life's an open road, darling, pedal with purpose!",
    "Chase success like it's a wild, untamed dream, sweetie!",
    "No horsing around, just ride towards your destiny!",
    "Sweat is the currency of champions, darling, spend it!",
    "Pedal like every revolution is a step towards glory!",
    "Life's a sprint, darling, give it all you've got!",
    "Climb hills like you're reaching for the stars, sweetie!",
    "I've ridden through storms, now it's your time to shine!",
    "Don't trot when you can gallop, honey, go full speed!",
    "Saddle up, sweetheart, and let ambition be your guide!",
    "Pedal with power, passion, and purpose, darling!",
    "Success is a marathon, honey, pace yourself for glory!",
    "Life's a journey, darling, make it an exhilarating ride!",
    "Climb hills like you're ascending the steps to triumph!",
    "Don't trot when you can sprint, sweetie, go for the gold!",
    "Saddle up, honey, and let determination be your compass!",
    "Pedal with pride, sweetie, and let success trail behind!",
    "Life's a race, darling, lead the pack with determination!",
    "Climb every hill with the grace of a gazelle, honey!",
    "No horsing around, just pedal power and perseverance!",
    "Sweat like success is your shadow, following your lead!",
    "Pedal with poise, sweetie, and let confidence be your guide!",
    "Life's a track, race it with resilience and roaring spirit!",
    "Don't trot when you can gallop, darling, go for the glory!",
    "Saddle up, honey, and ride towards the sunset of your dreams!",
    "Pedal with purpose, passion, and prowess, darling!",
    "Success is a marathon, honey, so pace yourself for triumph!",
    "Life's a journey, darling, make it a thrilling ride to the top!",
    "Climb hills like they're stepping stones to your grandest dreams!",
    "Don't trot when you can sprint, sweetie, go full throttle for gold!",
    "Saddle up, honey, and let determination be the wind beneath your wings!",
    "Pedal with pride, sweetie, and let success trail behind like a loyal companion!",
    "Life's a race, darling, lead the pack with determination and unwavering resolve!",
    "Climb every hill with the grace of a gazelle, honey, and let the summit be your throne!",
]

greetings = [
    "Well, well, well! Look who's ready to conquer the world of knowledge! Let's dive into the training sea, darling.",
    "Hello, sugar! Ready to turn this training session into a blockbuster? Buckle up, it's gonna be a wild ride.",
    "Hey there, kitten! Time to put on your learning hat and show the world what you're made of. Let's hustle!",
    "Hello, superstar! Today's lesson is your red carpet moment. Strut your stuff on the path to success!",
    "Oh, darling! The world is your stage, and today's script is all about brilliance. Let's nail this performance!",
    "Well, well, well! Ready to make waves in the sea of knowledge? You're the star, and the spotlight is on you!",
    "Hello, rockstar! Grab your metaphorical microphone, because today's lesson is your solo performance. Let's hit those high notes!",
    "Hey there, go-getter! Time to channel your inner fabulousness and sashay into the realm of wisdom. Let's make this session legendary!",
    "Greetings, trailblazer! Today's lesson is your canvas, and brilliance is your paint. Let's create a masterpiece together!",
    "Hello, gothic unicorn! Ready to sprinkle a bit of magic on our learning journey? Let's make today sparkle and shine!",
]

goodbyes = [
    "Well, that's a wrap, darling! Until next time, keep slaying the game. You're destined for greatness!",
    "Goodbye, superstar! Take a bow and remember, the sequel to today's success story is just around the corner. Break a leg out there!",
    "Time to bid adieu, kitten! Keep those claws sharp, and don't forget to leave a trail of brilliance wherever you go. Until our next rendezvous!",
    "Farewell, rockstar! The show may be over for today, but your encore is eagerly awaited. Keep shining in the spotlight of life!",
    "That's a wrap, darling! Until the next episode of our learning saga, keep the drama low and the success high. Take care, sugar!",
    "Goodbye, go-getter! The curtain falls on today's session, but the stage of your journey is vast. Break a leg out there, and we'll meet again soon!",
    "Time to exit stage left, my fabulous friend! Until our paths cross again, keep the applause of success echoing in your ears. You're a star!",
    "Farewell, trailblazer! Your journey is a blockbuster in the making. Keep scripting success, and I'll be waiting for the sequel. Ta-ta for now!",
    "Goodbye, maestro of brilliance! The symphony of your success plays on. Until the next movement, keep composing your masterpiece!",
    "And with a twirl and a flourish, it's time to say goodbye, gothic unicorn! Keep spreading magic in your wake, and we'll rendezvous in the enchanted forest of knowledge again soon!"
]
