quotes = [
    "Darling, seize the day like it's the last scene!",
    "Life is a script; rewrite it if you're not the star.",
    "In the grand theater of life, you're the leading role!",
    "Embrace the chaos; it's the dance of opportunity.",
    "Every setback is a plot twist in your success story.",
    "You're not a character; you're the entire narrative!",
    "Navigate life's rollercoaster with style and resilience.",
    "Turn setbacks into comebacks, darling. That's showbiz!",
    "In the drama of life, you're the Oscar-winning protagonist.",
    "Life's a production; make sure you're the star attraction.",
    "Dance through challenges; life is your choreography.",
    "Script your story with triumphs and unexpected joy.",
    "You're not a supporting role; you're the whole blockbuster!",
    "Carpe diem, my dear! Seize the spotlight in your story.",
    "Life's a series of scenes; make each one unforgettable.",
    "Darling, you're the director of your own epic tale.",
    "Turn heartaches into heartwarming plot twists, my love.",
    "You're not a walk-on part; you're the headlining act!",
    "Life is your masterpiece; don't be afraid to improvise.",
    "Create your narrative; don't let life write the script.",
    "In your life story, be the hero and the romantic lead!",
    "Navigate life's plot twists with grace and determination.",
    "Write your story with ink made of dreams and resilience.",
    "Life's a dazzling performance; make it a standing ovation.",
    "You're not in the wings; you're in the spotlight, darling!",
    "Every setback is a plot twist in your success story.",
    "Life's a grand premiere; make sure you steal the show.",
    "In the play of life, be both the lead and the understudy.",
    "Chase dreams with the ferocity of a Hollywood agent!",
    "You're not a cameo; you're the star of the feature film.",
    "In the theater of life, make each act a showstopper.",
    "Darling, life is a rom-com. Make it your love story.",
    "You're not a subplot; you're the main narrative, sweetie!",
    "Navigate the drama of life with the finesse of a diva.",
    "Every stumble is a dance step in your journey, my love.",
    "In life's sitcom, you're the lead with the best punchlines.",
    "You're not a walk-off; you're a runway sensation, darling!",
    "Life's a script; make sure your character is unforgettable.",
    "Turn the pages of life with the elegance of a ballerina.",
    "You're not an extra; you're the star of the spin-off!",
    "In life's soap opera, you're the charismatic lead, love.",
    "Script your destiny with boldness and unwavering grace.",
    "Life is a masterpiece; paint it with vibrant experiences.",
    "You're not a monologue; you're the entire soliloquy, darling!",
    "Every setback is a setup for a dazzling comeback, sweetie.",
    "In the sitcom of life, make sure you're the crowd favorite.",
    "You're not a subplot; you're the main story arc, my love.",
    "Life's a series; ensure each episode is Emmy-worthy.",
    "Write your story with ink made of dreams and resilience.",
    "You're not a supporting role; you're the grand finale!",
    "Darling, every setback is a plot twist in your triumph.",
    "Life's a stage; make sure your performance is iconic.",
    "In life's drama, you're the star; act accordingly.",
    "You're not a rerun; you're the blockbuster sequel, sweetie!",
    "Script your destiny with chapters of courage and triumph.",
    "Life is a symphony; make sure you're the lead melody.",
    "Darling, life is a dance floor; waltz through it with style.",
    "In the film of life, you're the lead; roll camera, my love!",
    "You're not a deleted scene; you're the director's cut, sweetie!",
    "Life's a comedy; make sure your punchlines are legendary.",
    "Navigate the screenplay of life with boldness and grace.",
    "You're not a flashback; you're the feature presentation!",
    "In the sitcom of life, be the character everyone loves.",
    "Life is a canvas; paint it with the hues of resilience.",
    "You're not a subplot; you're the thrilling climax, darling!",
    "Every stumble is a dance step in your journey, my love.",
    "In life's soap opera, you're the charismatic lead, love.",
    "Script your destiny with boldness and unwavering grace.",
    "Life is a masterpiece; paint it with vibrant experiences.",
    "You're not a monologue; you're the entire soliloquy, darling!",
    "Every setback is a setup for a dazzling comeback, sweetie.",
    "In the sitcom of life, make sure you're the crowd favorite.",
    "You're not a subplot; you're the main story arc, my love.",
    "Life's a series; ensure each episode is Emmy-worthy.",
    "Write your story with ink made of dreams and resilience.",
    "You're not a supporting role; you're the grand finale!",
    "Darling, every setback is a plot twist in your triumph.",
    "Life's a stage; make sure your performance is iconic.",
    "In life's drama, you're the star; act accordingly.",
    "You're not a rerun; you're the blockbuster sequel, sweetie!",
    "Script your destiny with chapters of courage and triumph.",
    "Life is a symphony; make sure you're the lead melody.",
    "Darling, life is a dance floor; waltz through it with style.",
    "In the film of life, you're the lead; roll camera, my love!",
    "You're not a deleted scene; you're the director's cut, sweetie!",
    "Life's a comedy; make sure your punchlines are legendary.",
    "Navigate the screenplay of life with boldness and grace.",
    "You're not a flashback; you're the feature presentation!",
    "In the sitcom of life, be the character everyone loves.",
    "Life is a canvas; paint it with the hues of resilience.",
    "You're not a subplot; you're the thrilling climax, darling!",
    "In every scene of life, ensure you steal the show, my love.",
    "Script your destiny with the elegance of a prima ballerina.",
    "Life's a musical; make sure your notes resonate, darling.",
    "You're not a behind-the-scenes; you're the main attraction!",
    "In the theater of life, play your part with Oscar-worthy grace.",
    "Navigate life's screenplay with the poise of a leading lady.",
    "You're not an extra; you're the star of your own show, sweetie!",
    "Script your success story with the finesse of a true artist.",
    "Darling, life is your grand premiere; shine on that red carpet!",
]

greetings = [
    "Hello, my fabulous friend! Ready for a star-studded day?",
    "Good day, darling! Let's paint this town with success!",
    "Well, well, well! Look who's here, ready to conquer!",
    "Greetings, starlight! Today is your purr-fect opportunity.",
    "Hello, darling! Time to dazzle the world with your charm.",
    "Good morning, superstar! Ready to shine bright today?",
    "Greetings, my glamorous companion! Let's own this day!",
    "Hello, fabulous! Get ready for a day of triumphs!",
    "Well, hello there, success story! Ready to unfold?",
    "Good day, my fabulous friend! Your time to shine is now!",
]

goodbyes = [
    "Until our paths cross again, stay fabulous, darling!",
    "Farewell, superstar! Keep sparkling on your journey!",
    "Goodbye for now, my dazzling friend! Keep slaying!",
    "Until next time, my fabulous companion! Stay fierce!",
    "Farewell, success story! Continue to script greatness!",
    "Goodbye, glamorous one! The world awaits your charm!",
    "Until we meet again, darling! Keep dazzling the world!",
    "Farewell for now, my triumphant friend! Own it!",
    "Goodbye, fabulous soul! Keep painting the town vibrant!",
    "Until next time, superstar! Your future is radiant!",
]
