quotes = [
    "Fo' shizzle, my athlete – grind now, shine later.",
    "Keep it real on the field – success is a marathon.",
    "No excuses, just results – that's how we roll.",
    "Stay on your hustle – greatness suits you, nephew.",
    "Puff, puff, pass the doubt – inhale success, exhale failure.",
    "On the field, drop it like it's hot – every damn time.",
    "Ain't no mountain too high – you're on a higher level.",
    "Roll with the punches – victory is your joint.",
    "Sweat like you're in a hotbox – success is your contact high.",
    "Game recognize game – keep it 100 on the training ground.",
    "D-O-double-G, trainin' like a G – that's the way.",
    "Ain't no drama, just karma – grind for your gold.",
    "Fo' real, athlete – you're the MVP of your destiny.",
    "Smoke doubt away, inhale success every day.",
    "On the field, you're the boss – bow wow, baby.",
    "Aim for the stars, shoot like a superstar.",
    "Run the game, don't let the game run you.",
    "Athlete, keep it smokin' – victory is your flavor.",
    "Droppin' wisdom on the track – you're the maestro.",
    "Play hard, stay true – victory is overdue.",
    "Kick ass, take names – you're the MVP, mane.",
    "On the field, blaze your own trail – it's your green path.",
    "Smokin' the competition – inhale victory, exhale doubt.",
    "Hustle harder, shine brighter – that's the Dogg way.",
    "Victory is your anthem – sing it loud and proud.",
    "Fo' shizzle, stay on the grind – success is yours.",
    "Roll with the winners – you're the headliner.",
    "Life's a game – play it like a champ, nephew.",
    "Stay high on ambition, athlete – the sky's the limit.",
    "Train like you're droppin' a chart-topping hit.",
    "D-O-double-G style – on the field, you're the main event.",
    "Ain't no backup, you're the lead – own the spotlight.",
    "No shortcuts, just high jumps – go for the gold.",
    "Smokin' the competition – you're the herbal remedy.",
    "Athlete, keep it OG – Original Grind, Original Glory.",
    "On the field, you're the chronic – unbeatable and iconic.",
    "In the game of life, you're the MVP – no debate.",
    "Fo' shizzle, work hard – success is a sweet melody.",
    "Rollin' on the field – victory is in your rotation.",
    "Athlete, stay chill – the top is where you belong.",
    "Smokin' the doubters – exhale success, inhale greatness.",
    "In the game of life, be the top dog – no leash.",
    "Ain't no half-steppin' – you're the full package.",
    "Rollin' with ambition – success is a smoke signal away.",
    "Fo' shizzle, break records – that's the athlete's code.",
    "On the field, drop bombs – you're the bomb, nephew.",
    "Stay on your grind – success is the grand finale.",
    "Puff, puff, pass the obstacles – conquer 'em all.",
    "In the game of life, you're the MVP – no cap.",
    "Ain't no lookin' back – victory's in the rearview mirror.",
    "Roll with resilience – success is your joint venture.",
    "Fo' shizzle, hustle – victory is a steady climb.",
    "Stay on the grind – success is your main squeeze.",
    "On the field, blaze your own trail – you're the firestarter.",
    "Keep it real on the track – success is the remix.",
    "No room for doubt – you're the maestro of victory.",
    "In the game of life, you're the MVP – keep it G.",
    "Fo' shizzle, train hard – success is the afterparty.",
    "Ain't no slowing down – victory is your turbo boost.",
    "On the field, drop wisdom – you're the professor of success.",
    "Roll with the winners – you're the VIP, nephew.",
    "Hustle like a champ – success is your encore.",
    "Fo' shizzle, rise and grind – success is your sunrise.",
    "Stay on the marathon – success is the finish line.",
    "On the field, be the boss – you're the CEO of victory.",
    "Puff, puff, pass the haters – inhale success, exhale doubt.",
    "Keep it smokin' on the grind – success is your strain.",
    "Athlete, stay legendary – victory is your legacy.",
    "Fo' shizzle, train like a G – success is the remix.",
    "Ain't no fakin' – you're the real deal, nephew.",
    "Roll with resilience – success is your second nature.",
    "On the field, drop beats – you're the rhythm of victory.",
    "Hustle like it's hot – success is your temperature.",
    "Fo' shizzle, own the game – victory is your birthright.",
    "Stay on the grind – success is your signature move.",
    "On the field, you're the vibe – success is your anthem.",
    "Puff, puff, pass the negativity – inhale success, exhale doubt.",
    "Keep it real on the track – success is the headline.",
    "Athlete, stay on your grind – victory is your playlist.",
    "Fo' shizzle, break the mold – success is your masterpiece.",
    "Ain't no stoppin' – you're the express train to victory.",
    "Rollin' with resilience – success is your co-pilot.",
    "On the field, drop gems – you're the jeweler of success.",
    "Hustle like a boss – success is your boardroom.",
    "Fo' shizzle, elevate your game – success is your altitude.",
    "Stay on the marathon – victory is your final lap.",
    "On the field, drop bars – you're the rapper of success.",
    "Puff, puff, pass the limitations – inhale success, exhale doubt.",
    "Keep it smokin' on the grind – success is your signature strain.",
    "Athlete, stay legendary – victory is your autobiography.",
    "Fo' shizzle, train like a G – success is your encore.",
    "Ain't no fakin' – you're the real deal, nephew.",
    "Roll with resilience – success",
]

greetings = [
    "Yo, what's crack-a-lackin', young grasshopper? Ready to roll up that knowledge and light it up? Let's get this session smokin'.",
    "What up, my mentee? Time to elevate that mindset, cuz we 'bout to drop some wisdom bombs up in here.",
    "Hey there, nephew! The game of learning is a marathon, not a sprint. So lace up, and let's hit this track together.",
    "Ayy, my apprentice! Ready to soak up the game like a sponge? We're gonna turn this training session into a chronic success.",
    "What's good, young blood? The learning vibes are in the air. Let's vibe out and get that education groove going.",
    "Hello, my protege! Today's lesson is smoother than a Snoop track. Get ready to ride the rhythm of knowledge.",
    "Hey, young player! The game is on, and we're here to win. Time to drop some lyrical wisdom bombs on this training beat.",
    "What's poppin', my student? Today's lesson is fresher than a West Coast breeze. Get ready for that knowledge breeze, nephew.",
    "Greetings, my pupil! We're in the dojo of wisdom, and you're about to become a black belt in knowledge. Let's roll.",
    "Yo, my apprentice! We're about to turn this training session into a laid-back masterpiece. Grab your mental shades and let's shine."
]

goodbyes = [
    "And with that, my mentee, it's time to peace out. Keep it real, stay true, and remember, knowledge is power. Stay lifted!",
    "Farewell, young scholar! Until we cross paths again, keep the mind elevated and the hustle activated. One love, my friend.",
    "Time to bounce, nephew! Keep the learning flame burning, and remember, the game never stops. Catch you on the flip side.",
    "I'm out, my apprentice! Until next time, keep soaking up that wisdom like a sponge. Stay cool, stay educated, and stay true.",
    "Gotta roll out, young blood! Keep the vibes positive, the mind elevated, and the hustle strong. Until our paths align again, stay blessed.",
    "It's been real, my protege! Until our next session, keep riding that knowledge wave. Stay chill, stay focused, and stay winning.",
    "Time to peace out, my student! Keep dropping those wisdom bombs and riding the wave of success. Until the next episode, stay fly.",
    "And with that, I'm ghost, young player! Until our knowledge paths intersect again, keep it smokin' and stay on that grind.",
    "Farewell, my pupil! Keep walking the path of wisdom, and remember, the journey is just as important as the destination. Stay legendary.",
    "I'm outta here, my apprentice! Keep the mind sharp, the hustle strong, and the knowledge flowing. Until next time, stay high on life."
]
